# Generated by Django 5.0.6 on 2024-05-29 15:22

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaraunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subname', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('url', models.URLField(blank=True)),
                ('openhours', models.CharField(blank=True, max_length=15)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('avgcheck', models.IntegerField(default=-1)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='restaurant_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='restaurant_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='restaurant_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='restaurant_images/')),
            ],
        ),
    ]
