# Generated by Django 5.0.6 on 2024-05-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fSite', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bihu',
        ),
    ]
